Add sigSize to calcPreVerificationGas
eth-infinitism/bundler pull request #20
Opened 2022-11-26 02:23 UTC by hazim-j

fix for #19

2022-11-26 12:08 UTC, drortirosh commented on packages/sdk/src/calcPreVerificationGas.ts
> +export function calcPreVerificationGas (userOp: Partial<NotPromise<UserOperationStruct>>, overheads?: Partial<GasOverheads>, sigSize?: number): number {
Instead if adding an extra parameter (and I'm sure there are more..), it is better to add it to the struct.
The usage becomes
calcPreVerificationGas(userOp, { sigSize:65 })

2022-11-27 10:04 UTC, drortirosh approved these changes

2022-11-27 10:05 UTC, drortirosh requested changes
please commit to "develop" branch instead.

2022-11-27 11:22 UTC, hazim-j commented
@drortirosh I don't think there is a `develop` branch in this repo (or at least not one I can see).

2022-11-27 15:17 UTC, drortirosh approved these changes

2022-11-27 15:17 UTC, merged