AA-513 single auth tuple for UserOperation
eth-infinitism/bundler pull request #232
Opened 2024-12-16 11:11 UTC by drortirosh

2024-12-16 12:36 UTC, forshtat requested changes
I have serious doubts that this change will be beneficial in the long term.

2024-12-16 12:36 UTC, forshtat commented on packages/utils/src/interfaces/UserOperation.ts
> +  eip7712auth?: EIP7702Authorization
I think you wanted to say `eip7702auth`?

2025-01-06 20:20 UTC, forshtat requested changes

2025-01-06 20:20 UTC, forshtat commented on packages/bundler/src/modules/BundleManager.ts
> +        chainId: `0x${parseInt(it.chainId.toString()).toString(16)}`.replace(/0x0*/, '0x') as PrefixedHexString,
Okay, this is getting out of hand. Please create a `getHexChainId()` function that would handle this bullshit.

2025-01-06 20:20 UTC, forshtat commented on packages/bundler/src/modules/BundleManager.ts
> +      const authorizationList = getAuthorizationList(entry.userOp)
Why did you inline this method? And any way, the `mergeEip7702Authorizations` is still there. I don't see a point in this change.

2025-01-06 20:20 UTC, forshtat commented on packages/bundler/src/modules/BundleManager.ts
> +    // TODO: need to replace
A new TODO for no apparent reason.

2025-01-06 20:20 UTC, forshtat commented on packages/bundler/src/modules/BundleManager.ts
> +      // }
Commented out code

2025-01-06 20:20 UTC, forshtat commented on packages/validation-manager/src/ValidationManager.ts
> +    }
Please extract to a separate function.

2025-01-06 20:20 UTC, forshtat commented on packages/validation-manager/src/ValidationManager.ts
> +      const authChainId = BigNumber.from(authorizationList[0].chainId)
You converted it into an array, so own up to it - iterate over the list and check all of it. It may become an actual array at any point in time and this will become a bug.

2025-01-06 20:20 UTC, forshtat commented on packages/validation-manager/src/ValidationManager.ts
> +      const currentChainId = BigNumber.from((this.entryPoint.provider as any)._network.chainId)
Maybe just accept the current ChainID as a config parameter, there is no need to dig it up again here.

2025-01-06 20:50 UTC, drortirosh commented on packages/bundler/src/modules/BundleManager.ts
> +      const authorizationList = getAuthorizationList(entry.userOp)
getAuthorizationList is for simpler support for erc4337 and rip7562: it always returns a list, and empty one of no tuple exists. This saves checking on each use.

2025-01-12 09:47 UTC, shahafn commented
@drortirosh I don't know how you did the merge, but something is not right:
This is the file on your branch:
https://github.com/eth-infinitism/bundler/blob/6541250791a6c1c77794b4a78b4d654b32aea0d3/packages/utils/src/RIP7560Utils.ts#L46

This is the file on master:

https://github.com/eth-infinitism/bundler/blob/2a6a3f4b4483e5ab6f3288825b4f9551c093ab2d/packages/utils/src/RIP7560Utils.ts#L48

They differ. Please undo the merge and redo it, since you might be removing necessary changes.

2025-01-12 10:20 UTC, shahafn commented on packages/validation-manager/src/ValidationManager.ts
> +      // relevant only for RIP-7562...
```suggestion
      // relevant only for RIP-7560...
```

2025-01-12 10:27 UTC, shahafn commented on packages/validation-manager/src/ValidationManager.ts
> +      // list is required to be of size=1. for completeness, we still scan it as a list.
Why? we have ValidationManager7560, that will handle it as a list, why do we need it here?

2025-01-12 10:30 UTC, shahafn approved these changes

2025-01-12 10:37 UTC, forshtat approved these changes

2025-01-12 10:39 UTC, merged